title : Course Site for Bush 631 -- Fall 2021
author :
  name : Rotem Dvir
  email : rdvir@tamu.edu
  github : rotemdvir
  twitter : nil
  feedburner : nil

markdown: kramdown
theme: jekyll-theme-architect
